version: "3.8"

services:
  inference:
    image: "inference:0.1.0"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./extractor:${WORKDIR}/extractor/
      - ./test_extractor:${WORKDIR}/test_extractor/
      - ./data:${WORKDIR}/data/
      - ./README.md:${WORKDIR}/README.md
    command: tail -f /dev/null
