version: "3.8"

services:
  inference:
    image: "inference:0.1.0"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - extractor.env
    volumes:
      - ./extractor:${WORKDIR}/extractor/
      - ./test_extractor:${WORKDIR}/test_extractor/
      - ./data:${WORKDIR}/data/
      - ./README.md:${WORKDIR}/README.md
      - ${AWS_CREDENTIAL_PATH}:${SECRETDIR}
    command: python extractor/extractor.py
